/**
 * Internal HTTP route table. Maps `(method, path)` to handlers.
 *
 * Most handlers are stubbed for v0; the real implementations land alongside
 * the dashboard wiring. Keeping the routing surface defined now means the
 * dashboard can be developed against a stable contract.
 *
 * Spec: gravel-cloud/docs/spec/api-surface.md §5
 */
import type { GravelRequest, GravelUser, ResolvedGravelConfig } from '../types.js'
import type { Database } from '../db/index.js'
import { json } from './index.js'
import {
  signSession,
  verifyPassword,
  SESSION_COOKIE,
  VIEW_AS_COOKIE,
} from '../auth/session.js'
import { attemptLogin, recordSuccess } from '../auth/rate-limit.js'
import {
  DASHBOARD_INDEX_HTML,
  DASHBOARD_LOGIN_HTML,
  DASHBOARD_ASSETS,
} from './dashboard-bundle.js'
import { getVersionInfo } from './version.js'

/**
 * Where to read the manifest / prompt files from. Honors
 * `GRAVEL_REPO_ROOT` so a dev running the dashboard's HMR Vite server
 * (whose `process.cwd()` is `packages/dashboard`) can point it at
 * their actual app's repo root and see real prompts. In production,
 * `process.cwd()` is the user's app root.
 */
function repoRoot(): string {
  return process.env.GRAVEL_REPO_ROOT ?? process.cwd()
}

interface RouteCtx {
  config: ResolvedGravelConfig
  /**
   * Null when the customer hasn't wired DATABASE_URL (prompts-only
   * install). Routes that need it must handle null and degrade
   * gracefully (see `/api/samples` for the pattern).
   */
  db: Database | null
  request: Request
  grRequest: GravelRequest
  path: string
  authed: GravelUser | null
}

export async function route(ctx: RouteCtx): Promise<Response> {
  const key = `${ctx.request.method} ${matchPath(ctx.path)}`
  const handler = ROUTES[key]
  if (handler) return await handler(ctx)

  // SPA fallthrough: client-side routes (`/prompts`, `/traces/abc`, etc.)
  // 404 on hard-refresh because the dashboard is a wouter SPA that owns
  // those URLs at runtime. Serve the shell HTML for any unmatched GET
  // that's NOT under `/api/` (real API) or `/_assets/` (Vite bundle).
  // The SPA's router takes over from there.
  if (
    ctx.request.method === 'GET' &&
    !ctx.path.startsWith('/api/') &&
    !ctx.path.startsWith('/_assets/')
  ) {
    return new Response(rewriteShell(DASHBOARD_INDEX_HTML, ctx.config), {
      status: 200,
      headers: {
        'content-type': 'text/html; charset=utf-8',
        'cache-control': 'no-cache',
      },
    })
  }

  return json({ error: 'not-found', path: ctx.path }, 404)
}

function matchPath(path: string): string {
  // Normalize :id-style segments for routing. Two id shapes in play:
  //   - Prefixed ids like `p_<hex>` (prompts, datasets, etc) — `<short
  //     prefix>_<hex chars>`, generated by `manifest/hash.ts`.
  //   - UUIDs (traces, eval runs) — hex with dashes, length 8+.
  // Plus the bundled-dashboard asset route, where the trailing segment is
  // an arbitrary content-hashed Vite filename (e.g. `index-D_tPEKcV.js`)
  // that matches neither id shape — collapse it to `:id` explicitly.
  let p = path
    .replace(/\/[a-z]{1,4}_[a-f0-9]{6,}(\/|$)/g, '/:id$1')
    .replace(/\/[a-f0-9-]{8,}(\/|$)/g, '/:id$1')
  p = p.replace(/^(\/_assets)\/[^/]+$/, '$1/:id')
  return p.replace(/\/$/, '') || '/'
}

const ROUTES: Record<string, (ctx: RouteCtx) => Promise<Response>> = {
  // Auth
  'GET /api/auth/me': async ({ authed, config }) => {
    if (!authed) return json({ error: 'unauthorized' }, 401)
    return json({
      user: authed,
      productName: config.productName,
      mountPath: config.mountPath,
      hideArtanisBranding: config.hideArtanisBranding,
    })
  },

  // Version info — admin only. Used by the dashboard to surface an
  // "update available" banner when the host's installed @artanis-ai/gravel
  // is behind npm @latest. See handler/version.ts for the cache + opt-out
  // (`GRAVEL_VERSION_CHECK_DISABLED=1`).
  'GET /api/version': async ({ authed }) => {
    if (!authed || authed.role !== 'admin') return json({ error: 'unauthorized' }, 401)
    return json(await getVersionInfo())
  },
  'POST /api/auth/login': async ({ request, config, grRequest }) => {
    if (!config.auth.defaultPassword) {
      return json({ error: 'password mode not configured' }, 400)
    }
    // Body parsing: form-encoded (login form) or JSON.
    const ctype = request.headers.get('content-type') ?? ''
    let password = ''
    if (ctype.includes('application/x-www-form-urlencoded')) {
      const form = await request.formData()
      password = String(form.get('password') ?? '')
    } else {
      try {
        const body = (await request.json()) as { password?: unknown }
        password = typeof body.password === 'string' ? body.password : ''
      } catch {
        password = ''
      }
    }
    const ip = clientIp(grRequest)
    const rate = attemptLogin(ip)
    if (!rate.allowed) {
      return new Response(
        JSON.stringify({
          error: 'too many attempts',
          retry_after_ms: rate.retryAfterMs ?? 60_000,
        }),
        {
          status: 429,
          headers: { 'content-type': 'application/json' },
        },
      )
    }
    if (!password || !verifyPassword(password, config.auth.defaultPassword)) {
      // Form-driven flow: bounce back to /login. JSON-driven: 401.
      const isForm = ctype.includes('application/x-www-form-urlencoded')
      if (isForm) {
        return new Response(null, {
          status: 303,
          headers: { location: `${config.mountPath}/login?error=1` },
        })
      }
      return json({ error: 'invalid password' }, 401)
    }
    recordSuccess(ip)
    const cookie = signSession(config.auth.defaultPassword)
    const headers = new Headers({ 'set-cookie': sessionCookieValue(cookie, request.url) })
    const isForm = ctype.includes('application/x-www-form-urlencoded')
    if (isForm) {
      // Trailing slash matters: relative asset URLs in the SPA shell
      // resolve against the directory of the URL. `/admin/ai` (no slash)
      // resolves `./assets/x.js` to `/admin/assets/x.js` which is wrong.
      // The trailing slash also keeps Vite happy in dev (its base-path
      // server only matches `${MOUNT_PATH}/`, so a redirect without the
      // slash 404s and the user sees a blank page).
      headers.set('location', `${config.mountPath || ''}/`)
      return new Response(null, { status: 303, headers })
    }
    headers.set('content-type', 'application/json')
    return new Response(JSON.stringify({ ok: true }), { status: 200, headers })
  },
  'POST /api/auth/logout': async ({ request, config }) => {
    const headers = new Headers({ 'set-cookie': sessionCookieClearValue(request.url) })
    headers.set('location', `${config.mountPath}/login`)
    return new Response(null, { status: 303, headers })
  },
  'POST /api/auth/view-as': async ({ request, authed, config }) => {
    if (!authed) return json({ error: 'unauthorized' }, 401)
    if (authed.role !== 'admin') return json({ error: 'admin only' }, 403)
    let mode: string | null = null
    try {
      const body = (await request.json()) as { mode?: unknown }
      mode = typeof body.mode === 'string' ? body.mode : null
    } catch {
      // form-style: cookie cleared
    }
    const headers = new Headers({
      'content-type': 'application/json',
    })
    if (mode === 'user') {
      headers.set('set-cookie', viewAsCookieValue('user', request.url))
    } else {
      headers.set('set-cookie', viewAsCookieClearValue(request.url))
    }
    void config
    return new Response(JSON.stringify({ ok: true, view_as: mode === 'user' ? 'user' : null }), {
      status: 200,
      headers,
    })
  },

  // Prompts (v0 surface) — list + read implemented from the manifest;
  // edit + submit-as-PR pending (depends on dashboard wiring).
  'GET /api/prompts': async () => {
    const { readManifest } = await import('../manifest/io.js')
    const { promises: fs } = await import('node:fs')
    const { join } = await import('node:path')
    const manifest = await readManifest(repoRoot())
    // Inline a short preview per prompt so the dashboard's grid can
    // render content without an N+1 fetch. Read failures degrade to
    // an empty preview rather than failing the whole list.
    const prompts = await Promise.all(
      manifest.prompts.map(async (p) => {
        let preview = ''
        try {
          const text = await fs.readFile(join(repoRoot(), p.path), 'utf8')
          const slice = p.type === 'embedded' ? text.slice(p.charStart, p.charEnd) : text
          preview = slice.trim().slice(0, 280)
        } catch {
          /* file gone since manifest scan; return blank preview */
        }
        return { ...p, preview }
      }),
    )
    return json({ prompts, last_scan_at: manifest.lastFullScanAt })
  },
  'GET /api/prompts/:id': async ({ path }) => {
    const id = path.split('/').pop()
    if (!id) return json({ error: 'missing id' }, 400)
    const { readManifest } = await import('../manifest/io.js')
    const { promises: fs } = await import('node:fs')
    const { join } = await import('node:path')
    const manifest = await readManifest(repoRoot())
    const entry = manifest.prompts.find((p) => p.id === id)
    if (!entry) return json({ error: 'not found' }, 404)

    const fullText = await fs.readFile(join(repoRoot(), entry.path), 'utf8')
    if (entry.type === 'file') {
      return json({ id: entry.id, type: entry.type, path: entry.path, content: fullText })
    }
    // Embedded: slice by char range.
    const content = fullText.slice(entry.charStart, entry.charEnd)
    return json({
      id: entry.id,
      type: entry.type,
      path: entry.path,
      varName: entry.varName,
      content,
    })
  },
  // Drafts live in the dashboard's localStorage (no server persistence).
  // The submit endpoint receives them inline — see POST /api/prompts/submit.
  'POST /api/prompts/submit': async ({ request, authed }) => {
    if (!authed) return json({ error: 'unauthorized' }, 401)
    let body: {
      title?: unknown
      description?: unknown
      submitterName?: unknown
      drafts?: unknown
    }
    try {
      body = (await request.json().catch(() => ({}))) as typeof body
    } catch {
      body = {}
    }
    // Validate the inline drafts payload.
    if (!Array.isArray(body.drafts) || body.drafts.length === 0) {
      return json(
        { error: 'no_drafts', message: 'drafts (non-empty array) required in request body' },
        400,
      )
    }
    const drafts: { promptId: string; newText: string }[] = []
    for (const raw of body.drafts) {
      if (
        typeof raw !== 'object' ||
        raw === null ||
        typeof (raw as { promptId?: unknown }).promptId !== 'string' ||
        typeof (raw as { newText?: unknown }).newText !== 'string'
      ) {
        return json(
          { error: 'invalid_draft', message: 'each draft needs string promptId + newText' },
          400,
        )
      }
      drafts.push({
        promptId: (raw as { promptId: string }).promptId,
        newText: (raw as { newText: string }).newText,
      })
    }
    const { getGhInstallState } = await import('../github/project-state.js')
    const ghState = await getGhInstallState()
    if (!ghState) {
      return json(
        {
          error: 'github_not_installed',
          message:
            'Gravel GitHub App is not installed on this project. Ask your developer to install it from the dashboard.',
        },
        409,
      )
    }
    // Mint a fresh installation token for this submit via the CP.
    const { mintInstallationToken } = await import('../github/app.js')
    const cpUrl = process.env.GRAVEL_CONTROL_PLANE_URL ?? 'https://gravel.artanis.ai'
    const projectId = process.env.GRAVEL_PROJECT_ID
    const apiKey = process.env.GRAVEL_API_KEY
    if (!projectId || !apiKey) {
      return json(
        { error: 'gravel_config_incomplete', message: 'GRAVEL_PROJECT_ID + GRAVEL_API_KEY required.' },
        500,
      )
    }
    let token: Awaited<ReturnType<typeof mintInstallationToken>>
    try {
      token = await mintInstallationToken({ controlPlaneUrl: cpUrl, apiKey, projectId })
    } catch (err) {
      return json(
        { error: 'github_token_mint_failed', message: (err as Error).message },
        502,
      )
    }
    const { submitDrafts, SubmitError, draftBranchFor } = await import('../prompts/submit.js')
    try {
      // submitterName comes from the dashboard form. Falls back to the
      // host's getUser() firstName when the field is left blank, which
      // mostly only happens for non-interactive callers.
      const submitterName =
        typeof body.submitterName === 'string' && body.submitterName.trim()
          ? body.submitterName.trim()
          : authed.firstName
      const result = await submitDrafts({
        repoRoot: repoRoot(),
        drafts,
        draftBranch: draftBranchFor(authed.id),
        accessToken: token.token,
        repoOwner: ghState.repoOwner,
        repoName: ghState.repoName,
        title: typeof body.title === 'string' ? body.title : undefined,
        description: typeof body.description === 'string' ? body.description : undefined,
        deFirstName: submitterName,
      })
      return json({ ok: true, pr: result })
    } catch (err) {
      if (err instanceof SubmitError) {
        return json({ error: err.code, message: err.message, details: err.details }, 400)
      }
      throw err
    }
  },

  // GitHub App install. Spec: gravel-cloud/docs/spec/prompts.md §6.
  // Per-user OAuth was removed 2026-05-07 (D-Q53 re-reversal).
  // Install state moved CP-side 2026-05-08 — the SDK queries the CP at
  // status-check + submit time; nothing is mirrored to the local DB.
  'GET /api/github/status': async () => {
    // `projectConfigured` lets the dashboard distinguish "the user
    // hasn't created a cloud project yet" from "they have one but
    // haven't installed the GitHub App on a repo." Without it, the
    // install banner shows for both cases and the install button
    // dies with `GRAVEL_PROJECT_ID not set` for users who never set
    // up the cloud side.
    const projectConfigured = !!process.env.GRAVEL_PROJECT_ID
    if (!projectConfigured) {
      return json({
        connected: false,
        projectConfigured: false,
        repoOwner: null,
        repoName: null,
        connectedAt: null,
      })
    }
    const { getGhInstallState } = await import('../github/project-state.js')
    let state: Awaited<ReturnType<typeof getGhInstallState>>
    try {
      state = await getGhInstallState()
    } catch (e) {
      // Don't 500 on a CP outage — the dashboard treats "no state" the
      // same as "uninstalled" and re-renders the install banner.
      return json({
        connected: false,
        projectConfigured: true,
        repoOwner: null,
        repoName: null,
        connectedAt: null,
        error: (e as Error).message,
      })
    }
    return json({
      connected: Boolean(state),
      projectConfigured: true,
      repoOwner: state?.repoOwner ?? null,
      repoName: state?.repoName ?? null,
      connectedAt: state?.installedAt ?? null,
    })
  },
  'GET /api/github/install': async ({ request, config }) => {
    const projectId = process.env.GRAVEL_PROJECT_ID
    if (!projectId) return json({ error: 'GRAVEL_PROJECT_ID not set' }, 500)
    const callback = new URL(`${config.mountPath}/api/github/install/callback`, request.url).toString()
    // Dev stub: bypass GitHub + control plane entirely. Used for the
    // fixture suite + UI iteration when the dev hasn't deployed the
    // CP yet. Submit later uses GRAVEL_GH_DEV_STUB_TOKEN (a PAT).
    if (process.env.GRAVEL_GH_DEV_STUB === '1') {
      const owner = process.env.GRAVEL_GH_DEV_REPO_OWNER
      const name = process.env.GRAVEL_GH_DEV_REPO_NAME
      if (!owner || !name) {
        return json(
          { error: 'GRAVEL_GH_DEV_STUB=1 requires GRAVEL_GH_DEV_REPO_OWNER + GRAVEL_GH_DEV_REPO_NAME' },
          500,
        )
      }
      // Round-trip straight back to ourselves so the SPA refetches
      // status — getGhInstallState() reads the same env vars.
      return json({ redirectUrl: `${callback}?gh=installed` })
    }
    // Bounce through the control plane so it can issue the signed
    // `state` parameter GitHub's install URL needs.
    const cpUrl = process.env.GRAVEL_CONTROL_PLANE_URL ?? 'https://gravel.artanis.ai'
    const start = new URL('/api/cli/github/install/start', cpUrl)
    start.searchParams.set('project_id', projectId)
    start.searchParams.set('return_to', callback)
    return json({ redirectUrl: start.toString() })
  },
  'GET /api/github/install/callback': async ({ request, config }) => {
    // The CP redirects here after the dev finishes the GitHub install
    // flow. CP has already persisted install state on its side — we
    // just bounce the browser to the dashboard with a success flag so
    // the SPA refetches /api/github/status.
    const { bustGhInstallStateCache } = await import('../github/project-state.js')
    bustGhInstallStateCache()
    void request
    return new Response(null, {
      status: 302,
      headers: { location: `${config.mountPath}/?gh=installed` },
    })
  },

  // Samples — one row per LLM call. Reads gravel_samples + feedback.
  'GET /api/samples': async ({ request, db }) => {
    const url = new URL(request.url)
    // Pre-check tables. The dashboard's OnboardingCard handles the
    // empty-tracing case; bouncing here keeps the SQL layer from
    // throwing "relation does not exist" on installs that took
    // prompts-only — and from crashing entirely when no DATABASE_URL
    // is configured (db === null).
    if (!db) {
      return json({ samples: [], total: 0, page: 1, page_size: 20 })
    }
    const { gravelTablesExist } = await import('../db/index.js')
    if (!(await gravelTablesExist(db))) {
      return json({ samples: [], total: 0, page: 1, page_size: 20 })
    }
    const { listSamples } = await import('../samples/query.js')
    const result = await listSamples(db, {
      env: url.searchParams.get('env') ?? undefined,
      model: url.searchParams.get('model') ?? undefined,
      status: (url.searchParams.get('status') ?? undefined) as
        | 'running'
        | 'completed'
        | 'errored'
        | undefined,
      q: url.searchParams.get('q') ?? undefined,
      from: url.searchParams.get('from') ?? undefined,
      to: url.searchParams.get('to') ?? undefined,
      page: url.searchParams.get('page') ? Number(url.searchParams.get('page')) : 1,
      pageSize: url.searchParams.get('page_size')
        ? Number(url.searchParams.get('page_size'))
        : undefined,
    })
    return json(result)
  },
  'GET /api/samples/:id': async ({ request, db }) => {
    const sampleId = new URL(request.url).pathname.split('/').pop()!
    if (!db) return json({ error: 'tables-missing' }, 404)
    const { gravelTablesExist } = await import('../db/index.js')
    if (!(await gravelTablesExist(db))) return json({ error: 'tables-missing' }, 404)
    const { getSampleDetail } = await import('../samples/query.js')
    const detail = await getSampleDetail(db, sampleId)
    if (!detail) return json({ error: 'not-found' }, 404)
    return json(detail)
  },
  'POST /api/samples/:id/feedback': async ({ request, db, authed }) => {
    if (!authed) return json({ error: 'unauthorized' }, 401)
    if (!db) return json({ error: 'tables-missing' }, 503)
    const sampleId = new URL(request.url).pathname.split('/').slice(-2, -1)[0]!
    let body: { score?: unknown; comment?: unknown; correction?: unknown }
    try {
      body = (await request.json()) as typeof body
    } catch {
      return json({ error: 'invalid JSON body' }, 400)
    }
    const score =
      body.score === 'positive' || body.score === 'negative' || body.score === 'neutral'
        ? body.score
        : null
    const { recordSampleFeedback } = await import('../samples/query.js')
    const result = await recordSampleFeedback(db, {
      sampleId,
      score,
      comment: typeof body.comment === 'string' ? body.comment : null,
      correction: typeof body.correction === 'string' ? body.correction : null,
      reporterUserId: authed.id,
    })
    return json({ ok: true, id: result.id })
  },

  // Dashboard SPA bootstrap. The Vite-built index.html is bundled at SDK
  // build time (see scripts/build-dashboard.mjs). Asset paths in the HTML
  // are emitted relative (`./assets/foo.js`) so we can rewrite them to
  // mount-relative URLs at request time without parsing HTML.
  'GET /': async ({ config }) =>
    new Response(rewriteShell(DASHBOARD_INDEX_HTML, config), {
      status: 200,
      headers: {
        'content-type': 'text/html; charset=utf-8',
        'cache-control': 'no-cache',
      },
    }),
  'GET /login': async ({ config }) =>
    new Response(rewriteShell(DASHBOARD_LOGIN_HTML, config), {
      status: 200,
      headers: {
        'content-type': 'text/html; charset=utf-8',
        'cache-control': 'no-cache',
      },
    }),

  // Bundled dashboard assets. Filenames are content-hashed by Vite, so
  // we cache aggressively. Public route — auth bypass lives in
  // handler/index.ts so the login page can load its JS/CSS too.
  'GET /_assets/:id': async ({ path }) => {
    const filename = decodeURIComponent(path.split('/').pop() ?? '')
    if (!filename || filename.includes('/') || filename.includes('..')) {
      return json({ error: 'invalid asset name' }, 400)
    }
    const asset = DASHBOARD_ASSETS[filename]
    if (!asset) return json({ error: 'asset not found', filename }, 404)
    const bytes = Buffer.from(asset.content, 'base64')
    return new Response(bytes, {
      status: 200,
      headers: {
        'content-type': asset.contentType,
        'cache-control': 'public, max-age=31536000, immutable',
        'content-length': String(bytes.byteLength),
      },
    })
  },
}

/**
 * Rewrite the bundled dashboard's relative asset URLs so they resolve
 * under the SDK mount path. Vite emits `src="./assets/index-XYZ.js"`
 * and `href="./assets/index-XYZ.css"`; we point them at our flat
 * `${mountPath}/_assets/<basename>` route.
 *
 * Also injects window globals the SPA reads at boot:
 *   - `__GRAVEL_MOUNT_PATH__` — used by the API client + login form
 *     to build absolute URLs without re-deriving from `location`.
 *   - `__GRAVEL_PRODUCT_NAME__` — used by the login + nav UI so the
 *     dashboard can be re-branded as the host product (the dashboard
 *     is meant to feel like part of the user's app, not a Gravel
 *     sign-in). Only injected when productName is set.
 *   - `__GRAVEL_HIDE_ARTANIS__` — paid-tier flag; SPA hides the
 *     "Powered by Artanis" footer when true.
 */
function rewriteShell(html: string, config: ResolvedGravelConfig): string {
  const prefix = config.mountPath.replace(/\/$/, '')
  const rewritten = html.replace(/(src|href)="\.\/assets\/([^"]+)"/g, (_, attr, file) => {
    const basename = String(file).split('/').pop() ?? file
    return `${attr}="${prefix}/_assets/${basename}"`
  })
  const globals: string[] = [`window.__GRAVEL_MOUNT_PATH__=${JSON.stringify(prefix)}`]
  if (config.productName) {
    globals.push(`window.__GRAVEL_PRODUCT_NAME__=${JSON.stringify(config.productName)}`)
  }
  if (config.hideArtanisBranding) {
    globals.push(`window.__GRAVEL_HIDE_ARTANIS__=true`)
  }
  const inject = `<script>${globals.join(';')}</script>`
  // Drop the inject just before the first <script type="module"> so it
  // runs before the SPA bundle reads the global. Fall back to <head> end
  // if the bundle's script tag has been renamed.
  if (rewritten.includes('<script type="module"')) {
    return rewritten.replace('<script type="module"', `${inject}\n    <script type="module"`)
  }
  return rewritten.replace('</head>', `${inject}\n  </head>`)
}

// ---- Cookie + IP helpers ----

function isHttps(requestUrl: string): boolean {
  try {
    return new URL(requestUrl).protocol === 'https:'
  } catch {
    return false
  }
}

function sessionCookieValue(value: string, requestUrl: string): string {
  const parts = [
    `${SESSION_COOKIE}=${value}`,
    'Path=/',
    'HttpOnly',
    'SameSite=Lax',
    'Max-Age=2592000', // 30 days
  ]
  if (isHttps(requestUrl)) parts.push('Secure')
  return parts.join('; ')
}

function sessionCookieClearValue(requestUrl: string): string {
  const parts = [
    `${SESSION_COOKIE}=`,
    'Path=/',
    'HttpOnly',
    'SameSite=Lax',
    'Max-Age=0',
  ]
  if (isHttps(requestUrl)) parts.push('Secure')
  return parts.join('; ')
}

function viewAsCookieValue(value: string, requestUrl: string): string {
  const parts = [
    `${VIEW_AS_COOKIE}=${value}`,
    'Path=/',
    'HttpOnly',
    'SameSite=Lax',
    'Max-Age=2592000',
  ]
  if (isHttps(requestUrl)) parts.push('Secure')
  return parts.join('; ')
}

function viewAsCookieClearValue(requestUrl: string): string {
  const parts = [
    `${VIEW_AS_COOKIE}=`,
    'Path=/',
    'HttpOnly',
    'SameSite=Lax',
    'Max-Age=0',
  ]
  if (isHttps(requestUrl)) parts.push('Secure')
  return parts.join('; ')
}

function clientIp(req: GravelRequest): string {
  // Best-effort IP — proxies usually set X-Forwarded-For.
  return (
    req.headers.get('x-forwarded-for')?.split(',')[0]?.trim() ??
    req.headers.get('x-real-ip') ??
    'unknown'
  )
}

