/**
 * Internal HTTP route table. Maps `(method, path)` to handlers.
 *
 * Most handlers are stubbed for v0; the real implementations land alongside
 * the dashboard wiring. Keeping the routing surface defined now means the
 * dashboard can be developed against a stable contract.
 *
 * Spec: gravel-cloud/docs/spec/api-surface.md §5
 */
import type { GravelRequest, GravelUser, ResolvedGravelConfig } from '../types.js'
import type { Database } from '../db/index.js'
import { json } from './index.js'
import {
  signSession,
  verifyPassword,
  SESSION_COOKIE,
  VIEW_AS_COOKIE,
} from '../auth/session.js'
import { attemptLogin, recordSuccess } from '../auth/rate-limit.js'
import {
  DASHBOARD_INDEX_HTML,
  DASHBOARD_LOGIN_HTML,
  DASHBOARD_ASSETS,
} from './dashboard-bundle.js'
import { getVersionInfo } from './version.js'

interface RouteCtx {
  config: ResolvedGravelConfig
  db: Database
  request: Request
  grRequest: GravelRequest
  path: string
  authed: GravelUser | null
}

export async function route(ctx: RouteCtx): Promise<Response> {
  const key = `${ctx.request.method} ${matchPath(ctx.path)}`
  const handler = ROUTES[key]
  if (handler) return await handler(ctx)

  // SPA fallthrough: client-side routes (`/prompts`, `/traces/abc`, etc.)
  // 404 on hard-refresh because the dashboard is a wouter SPA that owns
  // those URLs at runtime. Serve the shell HTML for any unmatched GET
  // that's NOT under `/api/` (real API) or `/_assets/` (Vite bundle).
  // The SPA's router takes over from there.
  if (
    ctx.request.method === 'GET' &&
    !ctx.path.startsWith('/api/') &&
    !ctx.path.startsWith('/_assets/')
  ) {
    return new Response(rewriteShell(DASHBOARD_INDEX_HTML, ctx.config), {
      status: 200,
      headers: {
        'content-type': 'text/html; charset=utf-8',
        'cache-control': 'no-cache',
      },
    })
  }

  return json({ error: 'not-found', path: ctx.path }, 404)
}

function matchPath(path: string): string {
  // Normalize :id-style segments for routing. Two id shapes in play:
  //   - Prefixed ids like `p_<hex>` (prompts, datasets, etc) — `<short
  //     prefix>_<hex chars>`, generated by `manifest/hash.ts`.
  //   - UUIDs (traces, eval runs) — hex with dashes, length 8+.
  // Plus the bundled-dashboard asset route, where the trailing segment is
  // an arbitrary content-hashed Vite filename (e.g. `index-D_tPEKcV.js`)
  // that matches neither id shape — collapse it to `:id` explicitly.
  let p = path
    .replace(/\/[a-z]{1,4}_[a-f0-9]{6,}(\/|$)/g, '/:id$1')
    .replace(/\/[a-f0-9-]{8,}(\/|$)/g, '/:id$1')
  p = p.replace(/^(\/_assets)\/[^/]+$/, '$1/:id')
  return p.replace(/\/$/, '') || '/'
}

const ROUTES: Record<string, (ctx: RouteCtx) => Promise<Response>> = {
  // Auth
  'GET /api/auth/me': async ({ authed, config }) => {
    if (!authed) return json({ error: 'unauthorized' }, 401)
    return json({
      user: authed,
      productName: config.productName,
      mountPath: config.mountPath,
      hideArtanisBranding: config.hideArtanisBranding,
    })
  },

  // Version info — admin only. Used by the dashboard to surface an
  // "update available" banner when the host's installed @artanis-ai/gravel
  // is behind npm @latest. See handler/version.ts for the cache + opt-out
  // (`GRAVEL_VERSION_CHECK_DISABLED=1`).
  'GET /api/version': async ({ authed }) => {
    if (!authed || authed.role !== 'admin') return json({ error: 'unauthorized' }, 401)
    return json(await getVersionInfo())
  },
  'POST /api/auth/login': async ({ request, config, grRequest }) => {
    if (!config.auth.defaultPassword) {
      return json({ error: 'password mode not configured' }, 400)
    }
    // Body parsing: form-encoded (login form) or JSON.
    const ctype = request.headers.get('content-type') ?? ''
    let password = ''
    if (ctype.includes('application/x-www-form-urlencoded')) {
      const form = await request.formData()
      password = String(form.get('password') ?? '')
    } else {
      try {
        const body = (await request.json()) as { password?: unknown }
        password = typeof body.password === 'string' ? body.password : ''
      } catch {
        password = ''
      }
    }
    const ip = clientIp(grRequest)
    const rate = attemptLogin(ip)
    if (!rate.allowed) {
      return new Response(
        JSON.stringify({
          error: 'too many attempts',
          retry_after_ms: rate.retryAfterMs ?? 60_000,
        }),
        {
          status: 429,
          headers: { 'content-type': 'application/json' },
        },
      )
    }
    if (!password || !verifyPassword(password, config.auth.defaultPassword)) {
      // Form-driven flow: bounce back to /login. JSON-driven: 401.
      const isForm = ctype.includes('application/x-www-form-urlencoded')
      if (isForm) {
        return new Response(null, {
          status: 303,
          headers: { location: `${config.mountPath}/login?error=1` },
        })
      }
      return json({ error: 'invalid password' }, 401)
    }
    recordSuccess(ip)
    const cookie = signSession(config.auth.defaultPassword)
    const headers = new Headers({ 'set-cookie': sessionCookieValue(cookie, request.url) })
    const isForm = ctype.includes('application/x-www-form-urlencoded')
    if (isForm) {
      // Trailing slash matters: relative asset URLs in the SPA shell
      // resolve against the directory of the URL. `/admin/ai` (no slash)
      // resolves `./assets/x.js` to `/admin/assets/x.js` which is wrong.
      // The trailing slash also keeps Vite happy in dev (its base-path
      // server only matches `${MOUNT_PATH}/`, so a redirect without the
      // slash 404s and the user sees a blank page).
      headers.set('location', `${config.mountPath || ''}/`)
      return new Response(null, { status: 303, headers })
    }
    headers.set('content-type', 'application/json')
    return new Response(JSON.stringify({ ok: true }), { status: 200, headers })
  },
  'POST /api/auth/logout': async ({ request, config }) => {
    const headers = new Headers({ 'set-cookie': sessionCookieClearValue(request.url) })
    headers.set('location', `${config.mountPath}/login`)
    return new Response(null, { status: 303, headers })
  },
  'POST /api/auth/view-as': async ({ request, authed, config }) => {
    if (!authed) return json({ error: 'unauthorized' }, 401)
    if (authed.role !== 'admin') return json({ error: 'admin only' }, 403)
    let mode: string | null = null
    try {
      const body = (await request.json()) as { mode?: unknown }
      mode = typeof body.mode === 'string' ? body.mode : null
    } catch {
      // form-style: cookie cleared
    }
    const headers = new Headers({
      'content-type': 'application/json',
    })
    if (mode === 'user') {
      headers.set('set-cookie', viewAsCookieValue('user', request.url))
    } else {
      headers.set('set-cookie', viewAsCookieClearValue(request.url))
    }
    void config
    return new Response(JSON.stringify({ ok: true, view_as: mode === 'user' ? 'user' : null }), {
      status: 200,
      headers,
    })
  },

  // Prompts (v0 surface) — list + read implemented from the manifest;
  // edit + submit-as-PR pending (depends on dashboard wiring).
  'GET /api/prompts': async () => {
    const { readManifest } = await import('../manifest/io.js')
    const manifest = await readManifest(process.cwd())
    return json({ prompts: manifest.prompts, last_scan_at: manifest.lastFullScanAt })
  },
  'GET /api/prompts/:id': async ({ path }) => {
    const id = path.split('/').pop()
    if (!id) return json({ error: 'missing id' }, 400)
    const { readManifest } = await import('../manifest/io.js')
    const { promises: fs } = await import('node:fs')
    const { join } = await import('node:path')
    const manifest = await readManifest(process.cwd())
    const entry = manifest.prompts.find((p) => p.id === id)
    if (!entry) return json({ error: 'not found' }, 404)

    const fullText = await fs.readFile(join(process.cwd(), entry.path), 'utf8')
    if (entry.type === 'file') {
      return json({ id: entry.id, type: entry.type, path: entry.path, content: fullText })
    }
    // Embedded: slice by char range.
    const content = fullText.slice(entry.charStart, entry.charEnd)
    return json({
      id: entry.id,
      type: entry.type,
      path: entry.path,
      varName: entry.varName,
      content,
    })
  },
  'PUT /api/prompts/:id': async ({ path, request, db, authed }) => {
    if (!authed) return json({ error: 'unauthorized' }, 401)
    const id = path.split('/').pop()
    if (!id) return json({ error: 'missing id' }, 400)
    let body: { newText?: unknown }
    try {
      body = (await request.json()) as { newText?: unknown }
    } catch {
      return json({ error: 'invalid JSON body' }, 400)
    }
    const newText = typeof body.newText === 'string' ? body.newText : null
    if (newText === null) return json({ error: 'newText (string) required' }, 400)
    const { readManifest } = await import('../manifest/io.js')
    const manifest = await readManifest(process.cwd())
    if (!manifest.prompts.find((p) => p.id === id)) {
      return json({ error: 'prompt not in manifest' }, 404)
    }
    const { ensureGravelUser } = await import('../prompts/user-extra.js')
    await ensureGravelUser(db, authed)
    const { upsertDraft, draftBranchFor } = await import('../prompts/drafts.js')
    const draftBranch = draftBranchFor(authed.id)
    const draft = await upsertDraft(db, {
      promptId: id,
      draftBranch,
      newText,
      editorUserId: authed.id,
    })
    return json({ draft, draftBranch })
  },
  'GET /api/prompts/drafts': async ({ db, authed }) => {
    if (!authed) return json({ error: 'unauthorized' }, 401)
    const { listDraftsForBranch, draftBranchFor } = await import('../prompts/drafts.js')
    const draftBranch = draftBranchFor(authed.id)
    const drafts = await listDraftsForBranch(db, draftBranch)
    return json({ draftBranch, drafts })
  },
  'DELETE /api/prompts/:id/draft': async ({ path, db, authed }) => {
    if (!authed) return json({ error: 'unauthorized' }, 401)
    // path is /api/prompts/:id/draft — :id is the segment after /prompts/
    const segments = path.split('/').filter(Boolean)
    const id = segments[2]
    if (!id) return json({ error: 'missing id' }, 400)
    const { deleteDraft, draftBranchFor } = await import('../prompts/drafts.js')
    await deleteDraft(db, { promptId: id, draftBranch: draftBranchFor(authed.id) })
    return json({ ok: true })
  },
  'POST /api/prompts/submit': async ({ request, db, authed }) => {
    if (!authed) return json({ error: 'unauthorized' }, 401)
    let body: { title?: unknown; description?: unknown; submitterName?: unknown }
    try {
      body = (await request.json().catch(() => ({}))) as typeof body
    } catch {
      body = {}
    }
    const { getGhInstallState } = await import('../github/project-state.js')
    const ghState = await getGhInstallState(db)
    if (!ghState) {
      return json(
        {
          error: 'github_not_installed',
          message:
            'Gravel GitHub App is not installed on this project. Ask your developer to install it from the dashboard.',
        },
        409,
      )
    }
    // Mint a fresh installation token for this submit. ~1-hour scope;
    // we don't cache because the token is single-use here (one PR per
    // mint), and the mint round-trip is fast.
    const { mintInstallationToken } = await import('../github/app.js')
    const cpUrl = process.env.GRAVEL_CONTROL_PLANE_URL ?? 'https://gravel.artanis.ai'
    let token: Awaited<ReturnType<typeof mintInstallationToken>>
    try {
      token = await mintInstallationToken({
        controlPlaneUrl: cpUrl,
        installBindingToken: ghState.bindingToken,
        installationId: ghState.installationId,
      })
    } catch (err) {
      return json(
        {
          error: 'github_token_mint_failed',
          message: (err as Error).message,
        },
        502,
      )
    }
    const { submitDrafts, SubmitError } = await import('../prompts/submit.js')
    const { draftBranchFor } = await import('../prompts/drafts.js')
    try {
      // submitterName comes from the dashboard form. Falls back to the
      // host's getUser() firstName when the field is left blank, which
      // mostly only happens for non-interactive callers.
      const submitterName =
        typeof body.submitterName === 'string' && body.submitterName.trim()
          ? body.submitterName.trim()
          : authed.firstName
      const result = await submitDrafts({
        db,
        repoRoot: process.cwd(),
        draftBranch: draftBranchFor(authed.id),
        accessToken: token.token,
        repoOwner: ghState.repoOwner,
        repoName: ghState.repoName,
        title: typeof body.title === 'string' ? body.title : undefined,
        description: typeof body.description === 'string' ? body.description : undefined,
        deFirstName: submitterName,
      })
      return json({ ok: true, pr: result })
    } catch (err) {
      if (err instanceof SubmitError) {
        return json({ error: err.code, message: err.message, details: err.details }, 400)
      }
      throw err
    }
  },

  // GitHub App install. Spec: gravel-cloud/docs/spec/prompts.md §6.
  // Per-user OAuth was removed 2026-05-07 (decisions.md D-Q53 re-reversal).
  'GET /api/github/status': async ({ db }) => {
    const { getGhInstallState } = await import('../github/project-state.js')
    const state = await getGhInstallState(db)
    return json({
      connected: Boolean(state),
      repoOwner: state?.repoOwner ?? null,
      repoName: state?.repoName ?? null,
      connectedAt: state?.installedAt ?? null,
    })
  },
  'GET /api/github/install': async ({ request, config }) => {
    const projectId = process.env.GRAVEL_PROJECT_ID
    if (!projectId) return json({ error: 'GRAVEL_PROJECT_ID not set' }, 500)
    const callback = new URL(`${config.mountPath}/api/github/install/callback`, request.url).toString()
    // Dev stub: bypass GitHub + control plane entirely. Used for the
    // local fixture suite + UI iteration when the dev hasn't deployed
    // the CP yet. Set GRAVEL_GH_DEV_STUB=1 + GRAVEL_GH_DEV_REPO_OWNER
    // + GRAVEL_GH_DEV_REPO_NAME to short-circuit. Submit later requires
    // GRAVEL_GH_DEV_STUB_TOKEN — a real PAT scoped to the stub repo.
    if (process.env.GRAVEL_GH_DEV_STUB === '1') {
      const owner = process.env.GRAVEL_GH_DEV_REPO_OWNER
      const name = process.env.GRAVEL_GH_DEV_REPO_NAME
      if (!owner || !name) {
        return json(
          { error: 'GRAVEL_GH_DEV_STUB=1 requires GRAVEL_GH_DEV_REPO_OWNER + GRAVEL_GH_DEV_REPO_NAME' },
          500,
        )
      }
      const stubCallback = new URL(callback)
      stubCallback.searchParams.set('installation_id', '0')
      stubCallback.searchParams.set('binding_token', 'dev-stub')
      stubCallback.searchParams.set('repo_owner', owner)
      stubCallback.searchParams.set('repo_name', name)
      return json({ redirectUrl: stubCallback.toString() })
    }
    // Bounce through the control plane so it can issue the signed
    // `state` parameter GitHub's install URL needs.
    const cpUrl = process.env.GRAVEL_CONTROL_PLANE_URL ?? 'https://gravel.artanis.ai'
    const start = new URL('/api/cli/github/install/start', cpUrl)
    start.searchParams.set('project_id', projectId)
    start.searchParams.set('return_to', callback)
    return json({ redirectUrl: start.toString() })
  },
  'GET /api/github/install/callback': async ({ request, db }) => {
    // The control plane redirects here after the dev finishes the
    // GitHub install flow. URL params:
    //   - installation_id: numeric, GitHub's identifier
    //   - binding_token  : long-lived JWT, used to mint installation tokens
    //   - repo_owner / repo_name: the repo the dev picked at install time
    const url = new URL(request.url)
    const installationIdRaw = url.searchParams.get('installation_id')
    const bindingToken = url.searchParams.get('binding_token')
    const repoOwner = url.searchParams.get('repo_owner')
    const repoName = url.searchParams.get('repo_name')
    if (!installationIdRaw || !bindingToken || !repoOwner || !repoName) {
      return json({ error: 'missing install params' }, 400)
    }
    const installationId = Number(installationIdRaw)
    if (!Number.isInteger(installationId) || installationId <= 0) {
      return json({ error: 'bad installation_id' }, 400)
    }
    const { setGhInstallState } = await import('../github/project-state.js')
    await setGhInstallState(db, {
      installationId,
      repoOwner,
      repoName,
      bindingToken,
      installedAt: new Date().toISOString(),
    })
    // Bounce the browser back to the dashboard root with a flag so the
    // SPA can refetch /api/github/status and dismiss the setup banner.
    return new Response(null, {
      status: 302,
      headers: { location: `${url.pathname.replace('/api/github/install/callback', '')}/?gh=installed` },
    })
  },

  // Traces — read from gravel_traces / observations / feedback.
  'GET /api/traces': async ({ request, db }) => {
    const url = new URL(request.url)
    const { listTraces } = await import('../tracing/query.js')
    const result = await listTraces(db, {
      env: url.searchParams.get('env') ?? undefined,
      model: url.searchParams.get('model') ?? undefined,
      status: (url.searchParams.get('status') ?? undefined) as
        | 'running'
        | 'completed'
        | 'errored'
        | undefined,
      q: url.searchParams.get('q') ?? undefined,
      from: url.searchParams.get('from') ?? undefined,
      to: url.searchParams.get('to') ?? undefined,
      page: url.searchParams.get('page') ? Number(url.searchParams.get('page')) : 1,
      pageSize: url.searchParams.get('page_size')
        ? Number(url.searchParams.get('page_size'))
        : undefined,
    })
    return json(result)
  },
  'GET /api/traces/:id': async ({ request, db }) => {
    const traceId = new URL(request.url).pathname.split('/').pop()!
    const { getTraceDetail } = await import('../tracing/query.js')
    const detail = await getTraceDetail(db, traceId)
    if (!detail) return json({ error: 'not-found' }, 404)
    return json(detail)
  },
  'POST /api/traces/:id/feedback': async ({ request, db, authed }) => {
    if (!authed) return json({ error: 'unauthorized' }, 401)
    const traceId = new URL(request.url).pathname.split('/').slice(-2, -1)[0]!
    let body: { score?: unknown; comment?: unknown; correction?: unknown }
    try {
      body = (await request.json()) as typeof body
    } catch {
      return json({ error: 'invalid JSON body' }, 400)
    }
    const score =
      body.score === 'positive' || body.score === 'negative' || body.score === 'neutral'
        ? body.score
        : null
    const { recordTraceFeedback } = await import('../tracing/query.js')
    const { ensureGravelUser } = await import('../prompts/user-extra.js')
    await ensureGravelUser(db, authed)
    const result = await recordTraceFeedback(db, {
      traceId,
      score,
      comment: typeof body.comment === 'string' ? body.comment : null,
      correction: typeof body.correction === 'string' ? body.correction : null,
      reporterUserId: authed.id,
    })
    return json({ ok: true, id: result.id })
  },

  // Datasets — collections of traces flagged for review/eval.
  'GET /api/datasets': async ({ db }) => {
    const { listDatasets } = await import('../datasets/query.js')
    const datasets = await listDatasets(db)
    // `runPipelineConfigured` is a flag for "can we trigger evals from
    // here yet?" — false until the eval-runner has been wired up to
    // a real LLM provider in the customer's config. v0: false.
    return json({ datasets, runPipelineConfigured: false })
  },
  'POST /api/datasets': async ({ request, db, authed }) => {
    if (!authed) return json({ error: 'unauthorized' }, 401)
    let body: { name?: unknown; description?: unknown }
    try {
      body = (await request.json()) as typeof body
    } catch {
      return json({ error: 'invalid JSON body' }, 400)
    }
    const name = typeof body.name === 'string' ? body.name.trim() : ''
    if (!name) return json({ error: 'name required' }, 400)
    const { createDataset } = await import('../datasets/query.js')
    const { ensureGravelUser } = await import('../prompts/user-extra.js')
    await ensureGravelUser(db, authed)
    const result = await createDataset(db, {
      name,
      description: typeof body.description === 'string' ? body.description : null,
      createdByUserId: authed.id,
    })
    return json({ ok: true, id: result.id })
  },
  'POST /api/datasets/:id/traces': async ({ request, db, authed }) => {
    if (!authed) return json({ error: 'unauthorized' }, 401)
    const datasetId = new URL(request.url).pathname.split('/').slice(-2, -1)[0]!
    let body: { traceId?: unknown; trace_id?: unknown }
    try {
      body = (await request.json()) as typeof body
    } catch {
      return json({ error: 'invalid JSON body' }, 400)
    }
    const traceId =
      (typeof body.traceId === 'string' && body.traceId) ||
      (typeof body.trace_id === 'string' && body.trace_id) ||
      null
    if (!traceId) return json({ error: 'traceId required' }, 400)
    const { addTraceToDataset } = await import('../datasets/query.js')
    const result = await addTraceToDataset(db, { datasetId, traceId })
    return json({ ok: true, id: result.id })
  },

  // Eval runs — list + create + state + cancel.
  // Full eval-runner kickoff (judge calls + per-row results) lands in
  // a follow-up; right now create returns a queued run that the dev
  // can hand to `runEval` from `evals/runner.ts` directly. The list /
  // get / cancel endpoints work end-to-end against `gravel_eval_runs`.
  'GET /api/evals/runs': async ({ db }) => {
    const { listEvalRuns } = await import('../evals/query.js')
    const runs = await listEvalRuns(db)
    return json({ runs })
  },
  'POST /api/evals/runs': async ({ request, db, authed }) => {
    if (!authed) return json({ error: 'unauthorized' }, 401)
    let body: { datasetId?: unknown; dataset_id?: unknown; type?: unknown; totalRows?: unknown; total_rows?: unknown }
    try {
      body = (await request.json()) as typeof body
    } catch {
      return json({ error: 'invalid JSON body' }, 400)
    }
    const datasetId =
      (typeof body.datasetId === 'string' && body.datasetId) ||
      (typeof body.dataset_id === 'string' && body.dataset_id) ||
      null
    if (!datasetId) return json({ error: 'datasetId required' }, 400)
    const type = body.type === 'live' ? 'live' : 'trace'
    const totalRows =
      typeof body.totalRows === 'number'
        ? body.totalRows
        : typeof body.total_rows === 'number'
          ? body.total_rows
          : 0
    const { createEvalRun } = await import('../evals/query.js')
    const { ensureGravelUser } = await import('../prompts/user-extra.js')
    await ensureGravelUser(db, authed)
    const result = await createEvalRun(db, {
      datasetId,
      type,
      triggeredByUserId: authed.id,
      totalRows,
    })
    return json({ ok: true, id: result.id, status: 'queued' })
  },
  'GET /api/evals/runs/:id': async ({ request, db }) => {
    const runId = new URL(request.url).pathname.split('/').pop()!
    const { getEvalRun } = await import('../evals/query.js')
    const run = await getEvalRun(db, runId)
    if (!run) return json({ error: 'not-found' }, 404)
    return json({ run })
  },
  'POST /api/evals/runs/:id/cancel': async ({ request, db, authed }) => {
    if (!authed) return json({ error: 'unauthorized' }, 401)
    const runId = new URL(request.url).pathname.split('/').slice(-2, -1)[0]!
    const { getEvalRun, setRunStatus } = await import('../evals/query.js')
    const run = await getEvalRun(db, runId)
    if (!run) return json({ error: 'not-found' }, 404)
    if (run.status === 'completed' || run.status === 'errored' || run.status === 'cancelled') {
      return json({ error: 'run is already terminal', status: run.status }, 409)
    }
    await setRunStatus(db, runId, 'cancelled', { completedAt: new Date() })
    return json({ ok: true, status: 'cancelled' })
  },

  // Mallet analysis (v3 paid)
  'GET /api/analysis/:id': async () => json({ error: 'not-implemented' }, 501),

  // Dashboard SPA bootstrap. The Vite-built index.html is bundled at SDK
  // build time (see scripts/build-dashboard.mjs). Asset paths in the HTML
  // are emitted relative (`./assets/foo.js`) so we can rewrite them to
  // mount-relative URLs at request time without parsing HTML.
  'GET /': async ({ config }) =>
    new Response(rewriteShell(DASHBOARD_INDEX_HTML, config), {
      status: 200,
      headers: {
        'content-type': 'text/html; charset=utf-8',
        'cache-control': 'no-cache',
      },
    }),
  'GET /login': async ({ config }) =>
    new Response(rewriteShell(DASHBOARD_LOGIN_HTML, config), {
      status: 200,
      headers: {
        'content-type': 'text/html; charset=utf-8',
        'cache-control': 'no-cache',
      },
    }),

  // Bundled dashboard assets. Filenames are content-hashed by Vite, so
  // we cache aggressively. Public route — auth bypass lives in
  // handler/index.ts so the login page can load its JS/CSS too.
  'GET /_assets/:id': async ({ path }) => {
    const filename = decodeURIComponent(path.split('/').pop() ?? '')
    if (!filename || filename.includes('/') || filename.includes('..')) {
      return json({ error: 'invalid asset name' }, 400)
    }
    const asset = DASHBOARD_ASSETS[filename]
    if (!asset) return json({ error: 'asset not found', filename }, 404)
    const bytes = Buffer.from(asset.content, 'base64')
    return new Response(bytes, {
      status: 200,
      headers: {
        'content-type': asset.contentType,
        'cache-control': 'public, max-age=31536000, immutable',
        'content-length': String(bytes.byteLength),
      },
    })
  },
}

/**
 * Rewrite the bundled dashboard's relative asset URLs so they resolve
 * under the SDK mount path. Vite emits `src="./assets/index-XYZ.js"`
 * and `href="./assets/index-XYZ.css"`; we point them at our flat
 * `${mountPath}/_assets/<basename>` route.
 *
 * Also injects window globals the SPA reads at boot:
 *   - `__GRAVEL_MOUNT_PATH__` — used by the API client + login form
 *     to build absolute URLs without re-deriving from `location`.
 *   - `__GRAVEL_PRODUCT_NAME__` — used by the login + nav UI so the
 *     dashboard can be re-branded as the host product (the dashboard
 *     is meant to feel like part of the user's app, not a Gravel
 *     sign-in). Only injected when productName is set.
 *   - `__GRAVEL_HIDE_ARTANIS__` — paid-tier flag; SPA hides the
 *     "Powered by Artanis" footer when true.
 */
function rewriteShell(html: string, config: ResolvedGravelConfig): string {
  const prefix = config.mountPath.replace(/\/$/, '')
  const rewritten = html.replace(/(src|href)="\.\/assets\/([^"]+)"/g, (_, attr, file) => {
    const basename = String(file).split('/').pop() ?? file
    return `${attr}="${prefix}/_assets/${basename}"`
  })
  const globals: string[] = [`window.__GRAVEL_MOUNT_PATH__=${JSON.stringify(prefix)}`]
  if (config.productName) {
    globals.push(`window.__GRAVEL_PRODUCT_NAME__=${JSON.stringify(config.productName)}`)
  }
  if (config.hideArtanisBranding) {
    globals.push(`window.__GRAVEL_HIDE_ARTANIS__=true`)
  }
  const inject = `<script>${globals.join(';')}</script>`
  // Drop the inject just before the first <script type="module"> so it
  // runs before the SPA bundle reads the global. Fall back to <head> end
  // if the bundle's script tag has been renamed.
  if (rewritten.includes('<script type="module"')) {
    return rewritten.replace('<script type="module"', `${inject}\n    <script type="module"`)
  }
  return rewritten.replace('</head>', `${inject}\n  </head>`)
}

// ---- Cookie + IP helpers ----

function isHttps(requestUrl: string): boolean {
  try {
    return new URL(requestUrl).protocol === 'https:'
  } catch {
    return false
  }
}

function sessionCookieValue(value: string, requestUrl: string): string {
  const parts = [
    `${SESSION_COOKIE}=${value}`,
    'Path=/',
    'HttpOnly',
    'SameSite=Lax',
    'Max-Age=2592000', // 30 days
  ]
  if (isHttps(requestUrl)) parts.push('Secure')
  return parts.join('; ')
}

function sessionCookieClearValue(requestUrl: string): string {
  const parts = [
    `${SESSION_COOKIE}=`,
    'Path=/',
    'HttpOnly',
    'SameSite=Lax',
    'Max-Age=0',
  ]
  if (isHttps(requestUrl)) parts.push('Secure')
  return parts.join('; ')
}

function viewAsCookieValue(value: string, requestUrl: string): string {
  const parts = [
    `${VIEW_AS_COOKIE}=${value}`,
    'Path=/',
    'HttpOnly',
    'SameSite=Lax',
    'Max-Age=2592000',
  ]
  if (isHttps(requestUrl)) parts.push('Secure')
  return parts.join('; ')
}

function viewAsCookieClearValue(requestUrl: string): string {
  const parts = [
    `${VIEW_AS_COOKIE}=`,
    'Path=/',
    'HttpOnly',
    'SameSite=Lax',
    'Max-Age=0',
  ]
  if (isHttps(requestUrl)) parts.push('Secure')
  return parts.join('; ')
}

function clientIp(req: GravelRequest): string {
  // Best-effort IP — proxies usually set X-Forwarded-For.
  return (
    req.headers.get('x-forwarded-for')?.split(',')[0]?.trim() ??
    req.headers.get('x-real-ip') ??
    'unknown'
  )
}

