/**
 * Internal HTTP route table. Maps `(method, path)` to handlers.
 *
 * Most handlers are stubbed for v0; the real implementations land alongside
 * the dashboard wiring. Keeping the routing surface defined now means the
 * dashboard can be developed against a stable contract.
 *
 * Spec: gravel-cloud/docs/spec/api-surface.md §5
 */
import type { GravelRequest, GravelUser, ResolvedGravelConfig } from '../types.js'
import type { Database } from '../db/index.js'
import { json } from './index.js'
import {
  signSession,
  verifyPassword,
  SESSION_COOKIE,
  VIEW_AS_COOKIE,
} from '../auth/session.js'
import { attemptLogin, recordSuccess } from '../auth/rate-limit.js'
import {
  DASHBOARD_INDEX_HTML,
  DASHBOARD_LOGIN_HTML,
  DASHBOARD_ASSETS,
} from './dashboard-bundle.js'

interface RouteCtx {
  config: ResolvedGravelConfig
  db: Database
  request: Request
  grRequest: GravelRequest
  path: string
  authed: GravelUser | null
}

export async function route(ctx: RouteCtx): Promise<Response> {
  const key = `${ctx.request.method} ${matchPath(ctx.path)}`
  const handler = ROUTES[key]
  if (!handler) return json({ error: 'not-found', path: ctx.path }, 404)
  return await handler(ctx)
}

function matchPath(path: string): string {
  // Normalize :id-style segments for routing. Two id shapes in play:
  //   - Prefixed ids like `p_<hex>` (prompts, datasets, etc) — `<short
  //     prefix>_<hex chars>`, generated by `manifest/hash.ts`.
  //   - UUIDs (traces, eval runs) — hex with dashes, length 8+.
  return path
    .replace(/\/[a-z]{1,4}_[a-f0-9]{6,}(\/|$)/g, '/:id$1')
    .replace(/\/[a-f0-9-]{8,}(\/|$)/g, '/:id$1')
    .replace(/\/$/, '') || '/'
}

const ROUTES: Record<string, (ctx: RouteCtx) => Promise<Response>> = {
  // Auth
  'GET /api/auth/me': async ({ authed, config }) => {
    if (!authed) return json({ error: 'unauthorized' }, 401)
    return json({
      user: authed,
      productName: config.productName,
      mountPath: config.mountPath,
      hideArtanisBranding: config.hideArtanisBranding,
    })
  },
  'POST /api/auth/login': async ({ request, config, grRequest }) => {
    if (!config.auth.defaultPassword) {
      return json({ error: 'password mode not configured' }, 400)
    }
    // Body parsing: form-encoded (login form) or JSON.
    const ctype = request.headers.get('content-type') ?? ''
    let password = ''
    if (ctype.includes('application/x-www-form-urlencoded')) {
      const form = await request.formData()
      password = String(form.get('password') ?? '')
    } else {
      try {
        const body = (await request.json()) as { password?: unknown }
        password = typeof body.password === 'string' ? body.password : ''
      } catch {
        password = ''
      }
    }
    const ip = clientIp(grRequest)
    const rate = attemptLogin(ip)
    if (!rate.allowed) {
      return new Response(
        JSON.stringify({
          error: 'too many attempts',
          retry_after_ms: rate.retryAfterMs ?? 60_000,
        }),
        {
          status: 429,
          headers: { 'content-type': 'application/json' },
        },
      )
    }
    if (!password || !verifyPassword(password, config.auth.defaultPassword)) {
      // Form-driven flow: bounce back to /login. JSON-driven: 401.
      const isForm = ctype.includes('application/x-www-form-urlencoded')
      if (isForm) {
        return new Response(null, {
          status: 303,
          headers: { location: `${config.mountPath}/login?error=1` },
        })
      }
      return json({ error: 'invalid password' }, 401)
    }
    recordSuccess(ip)
    const cookie = signSession(config.auth.defaultPassword)
    const headers = new Headers({ 'set-cookie': sessionCookieValue(cookie, request.url) })
    const isForm = ctype.includes('application/x-www-form-urlencoded')
    if (isForm) {
      headers.set('location', config.mountPath || '/')
      return new Response(null, { status: 303, headers })
    }
    headers.set('content-type', 'application/json')
    return new Response(JSON.stringify({ ok: true }), { status: 200, headers })
  },
  'POST /api/auth/logout': async ({ request, config }) => {
    const headers = new Headers({ 'set-cookie': sessionCookieClearValue(request.url) })
    headers.set('location', `${config.mountPath}/login`)
    return new Response(null, { status: 303, headers })
  },
  'POST /api/auth/view-as': async ({ request, authed, config }) => {
    if (!authed) return json({ error: 'unauthorized' }, 401)
    if (authed.role !== 'admin') return json({ error: 'admin only' }, 403)
    let mode: string | null = null
    try {
      const body = (await request.json()) as { mode?: unknown }
      mode = typeof body.mode === 'string' ? body.mode : null
    } catch {
      // form-style: cookie cleared
    }
    const headers = new Headers({
      'content-type': 'application/json',
    })
    if (mode === 'user') {
      headers.set('set-cookie', viewAsCookieValue('user', request.url))
    } else {
      headers.set('set-cookie', viewAsCookieClearValue(request.url))
    }
    void config
    return new Response(JSON.stringify({ ok: true, view_as: mode === 'user' ? 'user' : null }), {
      status: 200,
      headers,
    })
  },

  // Prompts (v0 surface) — list + read implemented from the manifest;
  // edit + submit-as-PR pending (depends on dashboard wiring).
  'GET /api/prompts': async () => {
    const { readManifest } = await import('../manifest/io.js')
    const manifest = await readManifest(process.cwd())
    return json({ prompts: manifest.prompts, last_scan_at: manifest.lastFullScanAt })
  },
  'GET /api/prompts/:id': async ({ path }) => {
    const id = path.split('/').pop()
    if (!id) return json({ error: 'missing id' }, 400)
    const { readManifest } = await import('../manifest/io.js')
    const { promises: fs } = await import('node:fs')
    const { join } = await import('node:path')
    const manifest = await readManifest(process.cwd())
    const entry = manifest.prompts.find((p) => p.id === id)
    if (!entry) return json({ error: 'not found' }, 404)

    const fullText = await fs.readFile(join(process.cwd(), entry.path), 'utf8')
    if (entry.type === 'file') {
      return json({ id: entry.id, type: entry.type, path: entry.path, content: fullText })
    }
    // Embedded: slice by char range.
    const content = fullText.slice(entry.charStart, entry.charEnd)
    return json({
      id: entry.id,
      type: entry.type,
      path: entry.path,
      varName: entry.varName,
      content,
    })
  },
  'PUT /api/prompts/:id': async ({ path, request, db, authed }) => {
    if (!authed) return json({ error: 'unauthorized' }, 401)
    const id = path.split('/').pop()
    if (!id) return json({ error: 'missing id' }, 400)
    let body: { newText?: unknown }
    try {
      body = (await request.json()) as { newText?: unknown }
    } catch {
      return json({ error: 'invalid JSON body' }, 400)
    }
    const newText = typeof body.newText === 'string' ? body.newText : null
    if (newText === null) return json({ error: 'newText (string) required' }, 400)
    const { readManifest } = await import('../manifest/io.js')
    const manifest = await readManifest(process.cwd())
    if (!manifest.prompts.find((p) => p.id === id)) {
      return json({ error: 'prompt not in manifest' }, 404)
    }
    const { ensureGravelUser } = await import('../prompts/user-extra.js')
    await ensureGravelUser(db, authed)
    const { upsertDraft, draftBranchFor } = await import('../prompts/drafts.js')
    const draftBranch = draftBranchFor(authed.id)
    const draft = await upsertDraft(db, {
      promptId: id,
      draftBranch,
      newText,
      editorUserId: authed.id,
    })
    return json({ draft, draftBranch })
  },
  'GET /api/prompts/drafts': async ({ db, authed }) => {
    if (!authed) return json({ error: 'unauthorized' }, 401)
    const { listDraftsForBranch, draftBranchFor } = await import('../prompts/drafts.js')
    const draftBranch = draftBranchFor(authed.id)
    const drafts = await listDraftsForBranch(db, draftBranch)
    return json({ draftBranch, drafts })
  },
  'DELETE /api/prompts/:id/draft': async ({ path, db, authed }) => {
    if (!authed) return json({ error: 'unauthorized' }, 401)
    // path is /api/prompts/:id/draft — :id is the segment after /prompts/
    const segments = path.split('/').filter(Boolean)
    const id = segments[2]
    if (!id) return json({ error: 'missing id' }, 400)
    const { deleteDraft, draftBranchFor } = await import('../prompts/drafts.js')
    await deleteDraft(db, { promptId: id, draftBranch: draftBranchFor(authed.id) })
    return json({ ok: true })
  },
  'POST /api/prompts/submit': async ({ request, db, authed }) => {
    if (!authed) return json({ error: 'unauthorized' }, 401)
    let body: { title?: unknown; description?: unknown }
    try {
      body = (await request.json().catch(() => ({}))) as typeof body
    } catch {
      body = {}
    }
    const { getUserGhState } = await import('../prompts/user-extra.js')
    const ghState = await getUserGhState(db, authed.id)
    if (!ghState.ghAccessToken || !ghState.repoOwner || !ghState.repoName) {
      return json(
        {
          error: 'github_not_connected',
          message:
            'Connect GitHub + select a repo before submitting. POST /api/github/repo to set the repo.',
        },
        409,
      )
    }
    const { submitDrafts, SubmitError } = await import('../prompts/submit.js')
    const { draftBranchFor } = await import('../prompts/drafts.js')
    try {
      const result = await submitDrafts({
        db,
        repoRoot: process.cwd(),
        draftBranch: draftBranchFor(authed.id),
        accessToken: ghState.ghAccessToken,
        repoOwner: ghState.repoOwner,
        repoName: ghState.repoName,
        title: typeof body.title === 'string' ? body.title : undefined,
        description: typeof body.description === 'string' ? body.description : undefined,
        deFirstName: authed.firstName,
      })
      return json({ ok: true, pr: result })
    } catch (err) {
      if (err instanceof SubmitError) {
        return json({ error: err.code, message: err.message, details: err.details }, 400)
      }
      throw err
    }
  },

  // GitHub OAuth connection. Spec: gravel-cloud/docs/spec/prompts.md §6.
  'GET /api/github/status': async ({ db, authed }) => {
    if (!authed) return json({ error: 'unauthorized' }, 401)
    const { getUserGhState } = await import('../prompts/user-extra.js')
    const state = await getUserGhState(db, authed.id)
    return json({
      connected: Boolean(state.ghAccessToken),
      repoOwner: state.repoOwner ?? null,
      repoName: state.repoName ?? null,
      connectedAt: state.ghConnectedAt ?? null,
    })
  },
  'POST /api/github/repo': async ({ request, db, authed }) => {
    if (!authed) return json({ error: 'unauthorized' }, 401)
    let body: { owner?: unknown; name?: unknown }
    try {
      body = (await request.json()) as { owner?: unknown; name?: unknown }
    } catch {
      return json({ error: 'invalid JSON body' }, 400)
    }
    const owner = typeof body.owner === 'string' ? body.owner : null
    const name = typeof body.name === 'string' ? body.name : null
    if (!owner || !name || !/^[\w.-]+$/.test(owner) || !/^[\w.-]+$/.test(name)) {
      return json({ error: 'owner and name (alphanumeric / . / _ / -) required' }, 400)
    }
    const { ensureGravelUser, patchUserGhState } = await import('../prompts/user-extra.js')
    await ensureGravelUser(db, authed)
    await patchUserGhState(db, authed.id, { repoOwner: owner, repoName: name })
    return json({ ok: true, repoOwner: owner, repoName: name })
  },
  'GET /api/github/connect': async ({ request, config }) => {
    const apiKey = process.env.GRAVEL_API_KEY
    const projectId = process.env.GRAVEL_PROJECT_ID
    if (!apiKey || !projectId) {
      return json({ error: 'GRAVEL_API_KEY / GRAVEL_PROJECT_ID not set in .env' }, 500)
    }
    const { startConnectFlow } = await import('../github/index.js')
    const callbackUrl = new URL(`${config.mountPath}/api/github/callback`, request.url).toString()
    const { redirectUrl } = startConnectFlow({ apiKey, projectId, callbackUrl })
    return json({ redirectUrl })
  },
  'GET /api/github/callback': async ({ request, db, authed, config }) => {
    if (!authed) return json({ error: 'unauthorized' }, 401)
    const apiKey = process.env.GRAVEL_API_KEY
    if (!apiKey) return json({ error: 'GRAVEL_API_KEY not set' }, 500)
    const url = new URL(request.url)
    const jwt = url.searchParams.get('session')
    if (!jwt) return json({ error: 'missing session parameter' }, 400)
    try {
      const { finalizeConnectCallback } = await import('../github/index.js')
      const result = finalizeConnectCallback({ apiKey, jwt })
      const { ensureGravelUser, patchUserGhState } = await import('../prompts/user-extra.js')
      await ensureGravelUser(db, authed)
      await patchUserGhState(db, authed.id, {
        ghAccessToken: result.ghAccessToken,
        ghConnectedAt: new Date().toISOString(),
      })
      // Bounce the browser back to a friendly settings page; the dashboard
      // SPA will re-fetch /api/github/status to update its UI.
      return new Response(null, {
        status: 302,
        headers: { location: `${config.mountPath}/?gh=connected` },
      })
    } catch (err) {
      return json({ error: (err as Error).message }, 400)
    }
  },

  // Traces (v1)
  'GET /api/traces': async () => json({ traces: [] }),
  'GET /api/traces/:id': async () => json({ error: 'not-implemented' }, 501),
  'POST /api/traces/:id/feedback': async () => json({ error: 'not-implemented' }, 501),

  // Datasets (v1)
  'GET /api/datasets': async () => json({ datasets: [] }),
  'POST /api/datasets': async () => json({ error: 'not-implemented' }, 501),
  'POST /api/datasets/:id/traces': async () => json({ error: 'not-implemented' }, 501),

  // Eval runs (v2)
  'GET /api/evals/runs': async () => json({ runs: [] }),
  'POST /api/evals/runs': async () => json({ error: 'not-implemented' }, 501),
  'GET /api/evals/runs/:id': async () => json({ error: 'not-implemented' }, 501),
  'POST /api/evals/runs/:id/cancel': async () => json({ error: 'not-implemented' }, 501),

  // Mallet analysis (v3 paid)
  'GET /api/analysis/:id': async () => json({ error: 'not-implemented' }, 501),

  // Billing — placeholder. v0/v1 have no paid surface; this returns the
  // free tier permanently. v2 will fetch from the control plane (the
  // judge dispatcher decrements credits there, not here).
  'GET /api/billing/credits': async () =>
    json({ tier: 'free', creditsRemaining: 0, paidSurfaceVersion: null }),
  'POST /api/billing/refresh': async () => json({ error: 'not-implemented' }, 501),

  // Dashboard SPA bootstrap. The Vite-built index.html is bundled at SDK
  // build time (see scripts/build-dashboard.mjs). Asset paths in the HTML
  // are emitted relative (`./assets/foo.js`) so we can rewrite them to
  // mount-relative URLs at request time without parsing HTML.
  'GET /': async ({ config }) =>
    new Response(rewriteShell(DASHBOARD_INDEX_HTML, config.mountPath), {
      status: 200,
      headers: {
        'content-type': 'text/html; charset=utf-8',
        'cache-control': 'no-cache',
      },
    }),
  'GET /login': async ({ config }) =>
    new Response(rewriteShell(DASHBOARD_LOGIN_HTML, config.mountPath), {
      status: 200,
      headers: {
        'content-type': 'text/html; charset=utf-8',
        'cache-control': 'no-cache',
      },
    }),

  // Bundled dashboard assets. Filenames are content-hashed by Vite, so
  // we cache aggressively. Public route — auth bypass lives in
  // handler/index.ts so the login page can load its JS/CSS too.
  'GET /_assets/:id': async ({ path }) => {
    const filename = decodeURIComponent(path.split('/').pop() ?? '')
    if (!filename || filename.includes('/') || filename.includes('..')) {
      return json({ error: 'invalid asset name' }, 400)
    }
    const asset = DASHBOARD_ASSETS[filename]
    if (!asset) return json({ error: 'asset not found', filename }, 404)
    const bytes = Buffer.from(asset.content, 'base64')
    return new Response(bytes, {
      status: 200,
      headers: {
        'content-type': asset.contentType,
        'cache-control': 'public, max-age=31536000, immutable',
        'content-length': String(bytes.byteLength),
      },
    })
  },
}

/**
 * Rewrite the bundled dashboard's relative asset URLs so they resolve
 * under the SDK mount path. Vite emits `src="./assets/index-XYZ.js"`
 * and `href="./assets/index-XYZ.css"`; we point them at our flat
 * `${mountPath}/_assets/<basename>` route.
 */
function rewriteShell(html: string, mountPath: string): string {
  const prefix = mountPath.replace(/\/$/, '')
  return html.replace(/(src|href)="\.\/assets\/([^"]+)"/g, (_, attr, file) => {
    const basename = String(file).split('/').pop() ?? file
    return `${attr}="${prefix}/_assets/${basename}"`
  })
}

// ---- Cookie + IP helpers ----

function isHttps(requestUrl: string): boolean {
  try {
    return new URL(requestUrl).protocol === 'https:'
  } catch {
    return false
  }
}

function sessionCookieValue(value: string, requestUrl: string): string {
  const parts = [
    `${SESSION_COOKIE}=${value}`,
    'Path=/',
    'HttpOnly',
    'SameSite=Lax',
    'Max-Age=2592000', // 30 days
  ]
  if (isHttps(requestUrl)) parts.push('Secure')
  return parts.join('; ')
}

function sessionCookieClearValue(requestUrl: string): string {
  const parts = [
    `${SESSION_COOKIE}=`,
    'Path=/',
    'HttpOnly',
    'SameSite=Lax',
    'Max-Age=0',
  ]
  if (isHttps(requestUrl)) parts.push('Secure')
  return parts.join('; ')
}

function viewAsCookieValue(value: string, requestUrl: string): string {
  const parts = [
    `${VIEW_AS_COOKIE}=${value}`,
    'Path=/',
    'HttpOnly',
    'SameSite=Lax',
    'Max-Age=2592000',
  ]
  if (isHttps(requestUrl)) parts.push('Secure')
  return parts.join('; ')
}

function viewAsCookieClearValue(requestUrl: string): string {
  const parts = [
    `${VIEW_AS_COOKIE}=`,
    'Path=/',
    'HttpOnly',
    'SameSite=Lax',
    'Max-Age=0',
  ]
  if (isHttps(requestUrl)) parts.push('Secure')
  return parts.join('; ')
}

function clientIp(req: GravelRequest): string {
  // Best-effort IP — proxies usually set X-Forwarded-For.
  return (
    req.headers.get('x-forwarded-for')?.split(',')[0]?.trim() ??
    req.headers.get('x-real-ip') ??
    'unknown'
  )
}

